SHOW DATABASES;

CREATE DATABASE PROJECT;
USE PROJECT;

CREATE TABLE RESTAURANT_INFO (
NAME VARCHAR(100),
STATE VARCHAR(100),
ADRESS VARCHAR(100),
TELE VARCHAR(100),
RUN_TIME_ID VARCHAR(100),
PRICE_ID INT(11),
PARKING VARCHAR(100),
 HOLIDAY VARCHAR(100), 
 SEAT INT(11),
 STORE_SERVICE_ID VARCHAR(100),
 STORE_TYPE TINYINT(1));
 


INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈광주유스퀘어',
	'광주 서구',
    '광주 서구 무진대로904스퀘어',
    '062-352-1031',
    6,
    3,
    '공영주차장',
    '연중무휴',
    300,
    8,
    0);
    
    INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 뉴코아 강남점',
	'서울시 서초구',
    '잠원로 51 뉴코아아울렛 강남점 1관 5층 애슐리퀸즈',
    '02-6082-1031',
    1,
    3,
    '유통 주차장',
    '유통점 휴무일',
    162,
    3,
    0);

 INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 뉴코아 부천점',
	'경기도 부천시',
    '송내대로 239 (상동) 부천뉴코아아울렛 4층',
    '032-624-8401',
    1,
    3,
    '뉴코아 아울렛 주차장',
    '설날 당일, 추석당일',
    340,
    9,
    0);

INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 뉴코아 인천점',
	'인천광역시 남동구',
    '인하로 485뉴코아 아울렛 인천점 9층',
    '032-441-1033',
    1,
    3,
    '아울렛 주차장',
    '뉴코아 아울렛 휴무일',
    236,
    5,
    0);
    
    INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 뉴코아 평촌점',
	'경기도 안양시 동안구',
    '동안로 119 (호계동) 평촌뉴코아아울렛 10층',
    '031-382-1443',
    1,
    3,
    '뉴코아 아울렛 주차장',
    '뉴코아 아울렛 휴무일',
    197,
    4,
    0);
    
     
    
     INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 롯데몰 수지점',
	'경기 용인시 수지구',
    '성복2로 38 롯데몰 수지점 4층 애슐리',
    '031-5174-4431',
    1,
    3,
    '없음',
    '연중무휴',
    186,
    1,
    0);
    
    INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 롯데몰 은평점',
	'서울특별시 은평구',
    '통일로 1050, 롯데몰 은평점 4층',
    '02-6975-5227',
    1,
    3,
    '없음',
    '연중무휴',
    214,
    5,
    0);
    
    INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 롯데백화점 김포공항점',
	'서울시 강서구',
    '하늘길 38 , 롯데백화점 5층 애슐리퀸즈',
    '02-6116-3553',
    1,
    3,
    '공영주차장',
    '백화점 휴무일',
    284,
    1,
    0);
    
    INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 미아사거리역점',
	'서울시 강북구',
    '도봉로 52 y-square 5층',
    '02-6415-0041',
    1,
    3,
    'y-square 주차장',
    '매주 3주째 월요일',
    344,
    2,
    1);
    
    INSERT INTO RESTAURANT_INFO (NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE) 
 VALUES ('퀸즈 서울대입구점',
	'서울특별시 관악구',
    '남부순환로 1820(봉천동) 라붐아울렛 9층',
    '02-6276-8200',
	1,
    3,
    '라붐 아울렛 주차장',
    '연중무류',
    280,
    3,
    0);
    
    
    
CREATE TABLE RUN_TIME_ID (
ID INT(11) PRIMARY KEY,
WEEKDAY VARCHAR(30),
WEEKDAY_END VARCHAR(30),
WEEKEND VARCHAR(30),
WEEKEND_END VARCHAR(30));


INSERT INTO RUN_TIME_ID(ID,WEEKDAY,WEEKDAY_END,WEEKEND,WEEKEND_END)
 VALUES (6,
 '평일 11:30~21:00',
 '(샐러드바 마감 21:00)',
 '주말 11:30~21:00',
 '(샐러드바 마감 21:00)');
 
 INSERT INTO RUN_TIME_ID (ID,WEEKDAY,WEEKDAY_END,WEEKEND,WEEKEND_END)
  VALUES (1,
  '평일 11:00~21:00',
  '(샐러드바 마감 21:00)',
  '주말 11:30~21:00',
  '(샐러드바 마감 21:00)');


CREATE TABLE PRICE_ID (
ID INT(11) PRIMARY KEY,
WEEKDAY_DINNER INT(11),
WEEKEND_DINNER INT(11),
ELEMENTARY INT(11),
INFANT INT(11));



INSERT INTO PRICE_ID(ID, WEEKDAY_DINNER,WEEKEND_DINNER,ELEMENTARY,INFANT)
 VALUES (3,
 17900,
 25900,
 27900,
 12900,
 7900);



CREATE TABLE STORE_SERVICE_ID (
ID INT(11) PRIMARY KEY,
WINE TINYINT(1),
BEER TINYINT(1),
DELIVERY TINYINT(1),
KIDS_ROOM TINYINT(1),
NURSING_ROOM TINYINT(1));



INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (1,
 0,
 1,
 0,
 0,
 0);
 
 
 INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (2,
 1,
 1,
 1,
 0,
 1);
 
 
 INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (3,
 1,
 1,
 0,
 0,
 0);
 
 
 INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (4,
 0,
 1,
 1,
 0,
 0);
 
 
 INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (5,
 1,
 1,
 1,
 0,
 0);
 
 
 INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (8,
 1,
 1,
 1,
 1,
 1);
 
 
 INSERT INTO STORE_SERVICE_ID (ID,WINE,BEER,DELIVERY,KIDS_ROOM,NURSING_ROOM)
 VALUES (9,
 1,
 1,
 0,
 1,
 0);
 
 
 SELECT RESTAURANT_INFO.NAME,STATE,ADRESS,TELE,RUN_TIME_ID,PRICE_ID,PARKING,HOLIDAY,SEAT,STORE_SERVICE_ID,STORE_TYPE
 FROM RESTAURANT_INFO
 LEFT JOIN RUN_TIME_ID
 ON RESTAURANT_INFO.RUN_TIME_ID = RUN_TIME_ID.ID
 LEFT JOIN PRICE_ID
 ON RESTAURANT_INFO.RUN_TIME_ID = PRICE_ID.ID
 LEFT JOIN STORE_SERVICE_ID
 ON RESTAURANT_INFO.RUN_TIME_ID = STORE_SERVICE_ID.ID;
 
 
 